title: blof
author: anna
description: my loofly bloggity blog

remote_theme: jekyll/minima

minima:
  date_format: "%-d %b, %Y"
  skin: solarized-dark

#theme: jekyll-theme-minimal

plugins:
        - jekyll-feed
